name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Virtualhere Client
        uses: ./
        with:
          vc-version: '>=5.5.6'

      - name: Run Add Hub
        run: VC-Hub-Add -Server "${{ secrets.VIRTUALHERE_SERVER }}"

      - name: Run Find USB Token
        run: |
          $success, $tokenAddress, $already = VC-Device-Add -DeviceName "${{ vars.VIRTUALHERE_DEVICE }}"

          if (!$success) {
            throw [System.Exception]::new("Device Not Added. ${{ vars.VIRTUALHERE_DEVICE }}")
          }

          "TOKEN_ADDRESS=$tokenAddress" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "ALREADY=$already" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        id: find-usb-token

      - name: Run Check Add Device
        run: VC-Pipe "LIST"

      - name: Post Run Stop
        if: always() && steps.find-usb-token.outputs.ALREADY == 'false'
        run: |
          VC-Pipe "STOP USING,${{ steps.find-usb-token.outputs.TOKEN_ADDRESS }}"
          VC-Pipe "MANUAL HUB REMOVE,${{ secrets.VIRTUALHERE_SERVER }}"
